In [63]:
# Dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from keras.utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense


In [64]:
data=pd.read_csv('output/horseData_20180804v1.1.csv')
data.head()

distance    purse  track  age  odds  pp_start  j_starts  j_first  j_second  \
0     800.0  26000.0      1    4   4.4         6         5        0         1   
1     800.0  26000.0      1    6  13.9         2        15        0         1   
2     800.0  26000.0      1    5  11.1         1        42       10         3   
3     800.0  26000.0      1    7   3.9         7        45        2         5   
4     800.0  26000.0      1    4   3.1         5        51        4         7   

   j_third   ...     j_top_3  j_top_3_perc  t_starts  t_first  t_second  \
0        0   ...           1          0.20         7        0         0   
1        3   ...           4          0.27         3        0         1   
2        5   ...          18          0.43        24        2         4   
3        3   ...          10          0.22         5        0         2   
4        7   ...          18          0.35        51        9         9   

   t_third  t_total_win_amt  t_win_perc  t_top_3  winloss  
0        0             3630        0.00     0.00        0  
1        1             7465        0.00     0.67        1  
2        4           179100        0.08     0.42        0  
3        1            23065        0.00     0.60        0  
4        5           435875        0.18     0.45        1  

[5 rows x 22 columns]

In [65]:
cols=['distance',
 'track',
 'age',
 'odds',
 'pp_start',
 'j_starts',
 'j_first',
 'j_second',
 'j_third',
 'j_total_win_amt',
 'j_win_perc',
 'j_top_3',
 'j_top_3_perc',
 't_starts',
 't_first',
 't_second',
 't_third',
 't_total_win_amt',
 't_win_perc',
 't_top_3']

In [66]:
# X = data.drop(["winloss","pp_finish","speed_rating"], axis=1)
X=data[cols]
y = data["winloss"]
print(X.shape, y.shape)

(804, 20) (804,)


In [67]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, random_state=1, stratify=y)
X_scaler = StandardScaler().fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


# Step 1: Label-encode data set
label_encoder = LabelEncoder()
label_encoder.fit(y_train)
encoded_y_train = label_encoder.transform(y_train)
encoded_y_test = label_encoder.transform(y_test)

# Step 2: Convert encoded labels to one-hot-encoding
y_train_categorical = to_categorical(encoded_y_train)
y_test_categorical = to_categorical(encoded_y_test)

In [68]:
# Create model and add layers
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=20))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=2, activation='softmax'))

In [69]:
# Compile and fit the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=250,
    shuffle=True,
    verbose=2
)

Epoch 1/250
 - 0s - loss: 0.6432 - acc: 0.6219
Epoch 2/250
 - 0s - loss: 0.5353 - acc: 0.7164
Epoch 3/250
 - 0s - loss: 0.4978 - acc: 0.7430
Epoch 4/250
 - 0s - loss: 0.4776 - acc: 0.7546
Epoch 5/250
 - 0s - loss: 0.4645 - acc: 0.7562
Epoch 6/250
 - 0s - loss: 0.4533 - acc: 0.7711
Epoch 7/250
 - 0s - loss: 0.4379 - acc: 0.7977
Epoch 8/250
 - 0s - loss: 0.4275 - acc: 0.7894
Epoch 9/250
 - 0s - loss: 0.4178 - acc: 0.7894
Epoch 10/250
 - 0s - loss: 0.4124 - acc: 0.8109
Epoch 11/250
 - 0s - loss: 0.4026 - acc: 0.8027
Epoch 12/250
 - 0s - loss: 0.3896 - acc: 0.8242
Epoch 13/250
 - 0s - loss: 0.3804 - acc: 0.8292
Epoch 14/250
 - 0s - loss: 0.3694 - acc: 0.8259
Epoch 15/250
 - 0s - loss: 0.3618 - acc: 0.8425
Epoch 16/250
 - 0s - loss: 0.3455 - acc: 0.8574
Epoch 17/250
 - 0s - loss: 0.3369 - acc: 0.8574
Epoch 18/250
 - 0s - loss: 0.3269 - acc: 0.8607
Epoch 19/250
 - 0s - loss: 0.3244 - acc: 0.8657
Epoch 20/250
 - 0s - loss: 0.3181 - acc: 0.8607
Epoch 21/250
 - 0s - loss: 0.3243 - acc: 0.8541
E

Epoch 171/250
 - 0s - loss: 0.0096 - acc: 0.9983
Epoch 172/250
 - 0s - loss: 0.0125 - acc: 0.9934
Epoch 173/250
 - 0s - loss: 0.0120 - acc: 0.9950
Epoch 174/250
 - 0s - loss: 0.0116 - acc: 0.9967
Epoch 175/250
 - 0s - loss: 0.0112 - acc: 0.9934
Epoch 176/250
 - 0s - loss: 0.0128 - acc: 0.9950
Epoch 177/250
 - 0s - loss: 0.0104 - acc: 0.9967
Epoch 178/250
 - 0s - loss: 0.0112 - acc: 0.9950
Epoch 179/250
 - 0s - loss: 0.0150 - acc: 0.9950
Epoch 180/250
 - 0s - loss: 0.0106 - acc: 0.9950
Epoch 181/250
 - 0s - loss: 0.0134 - acc: 0.9950
Epoch 182/250
 - 0s - loss: 0.0139 - acc: 0.9950
Epoch 183/250
 - 0s - loss: 0.0084 - acc: 0.9967
Epoch 184/250
 - 0s - loss: 0.0073 - acc: 0.9983
Epoch 185/250
 - 0s - loss: 0.0079 - acc: 0.9983
Epoch 186/250
 - 0s - loss: 0.0074 - acc: 0.9967
Epoch 187/250
 - 0s - loss: 0.0063 - acc: 0.9967
Epoch 188/250
 - 0s - loss: 0.0073 - acc: 0.9967
Epoch 189/250
 - 0s - loss: 0.0087 - acc: 0.9967
Epoch 190/250
 - 0s - loss: 0.0106 - acc: 0.9983
Epoch 191/250
 - 0s 

In [131]:
model.evaluate(X_test_scaled, y_test_categorical, verbose=2)

[2.0498668880604987, 0.6716417922309382]

In [71]:
# X_train_scaled

In [72]:
# my_test = X.iloc[1].values.reshape(1,-1)

# predict_scaled = X_scaler.transform(my_test)
# predict_scaled

In [73]:
# model.predict(predict_scaled)

In [74]:
# loss = [0,1]
# victory = [1,0]

In [76]:
X_predict=pd.read_csv('resources/SaturdayRaces.csv')
X_predict.head()

distance  track  age  odds  pp_start  j_starts  j_first  j_second  j_third  \
0       900      0    7   6.0         7        28        3         1        1   
1       650      1    3   5.0         1        63        9         6        5   
2       550      1    4  10.0         2        63        9         6        5   
3       500      0    6  30.0        10         2        0         0        0   
4       550      1    3  12.0         3        12        1         1        2   

   j_total_win_amt  j_win_perc  j_top_3  j_top_3_perc  t_starts  t_first  \
0            66200        0.11        5          0.18         5        2   
1           314435        0.14       20          0.32        12        2   
2           314435        0.14       20          0.32         4        0   
3              690        0.00        0          0.00         1        0   
4            25830        0.08        4          0.33         2        0   

   t_second  t_third  t_total_win_amt  t_win_perc  t_top_3  
0         0        1            28890        0.40     0.60  
1         2        0           114515        0.17     0.33  
2         0        0             1435        0.00     0.00  
3         0        0              345        0.00     0.00  
4         0        0             2145        0.00     0.00

In [85]:
X_scaler = StandardScaler().fit(X_predict)
X_pred_scaled = X_scaler.transform(X_predict)
X_pred_scaled

array([[ 2.09700592e+00, -1.29099445e+00,  2.54826821e+00,
        -3.10058644e-01,  9.90621129e-01, -5.56528662e-01,
        -5.88591287e-01, -1.32450944e+00, -1.21684187e+00,
        -1.06955277e+00, -1.11535693e-01, -1.23081697e+00,
        -1.33082673e+00, -8.39969568e-01, -2.40163556e-01,
        -8.06830092e-01, -6.26985834e-01, -7.09999406e-01,
         3.07564568e+00,  1.39394248e+00],
       [ 3.31106197e-01,  7.74596669e-01, -3.12945219e-01,
        -4.76347079e-01, -1.46885202e+00,  1.53981249e+00,
         1.40569448e+00,  7.13197391e-01,  2.25341087e-01,
         1.69110161e-01,  3.47354015e-01,  9.68161237e-01,
        -8.69942366e-02, -4.16201137e-01, -2.40163556e-01,
        -1.09031094e-01, -1.13707600e+00, -2.44670132e-01,
         6.00782101e-01, -9.74784952e-03],
       [-3.75253690e-01,  7.74596669e-01,  4.02358139e-01,
         3.55095096e-01, -1.05893983e+00,  1.53981249e+00,
         1.40569448e+00,  7.13197391e-01,  2.25341087e-01,
         1.69110161e-01,  3.4

In [88]:
my_test = X_pred_scaled[1].reshape(1,-1)

model.predict(my_test)

array([[0.00112002, 0.99887997]], dtype=float32)

In [90]:
predictions = model.predict_on_batch(X_pred_scaled)
predictions

array([[9.99999881e-01, 7.46689039e-08],
       [1.12001819e-03, 9.98879969e-01],
       [9.99998569e-01, 1.40754582e-06],
       [1.00000000e+00, 1.80180980e-21],
       [9.99226570e-01, 7.73370150e-04],
       [1.00000000e+00, 1.46571399e-09],
       [7.76201546e-01, 2.23798439e-01],
       [9.97257054e-01, 2.74299295e-03],
       [1.00000000e+00, 8.42857034e-13],
       [4.23544770e-05, 9.99957681e-01],
       [9.99976397e-01, 2.35577390e-05],
       [1.00000000e+00, 1.03790261e-13],
       [9.99982595e-01, 1.74384804e-05],
       [8.35053444e-01, 1.64946496e-01],
       [4.15207773e-01, 5.84792197e-01],
       [4.40871483e-03, 9.95591283e-01],
       [2.25178184e-07, 9.99999762e-01],
       [1.00000000e+00, 1.90477634e-09],
       [9.99999881e-01, 1.60969520e-07],
       [9.88300443e-01, 1.16996132e-02],
       [1.00619486e-02, 9.89938021e-01],
       [1.81655693e-07, 9.99999762e-01],
       [9.99987364e-01, 1.25876995e-05],
       [1.00000000e+00, 3.73292730e-10],
       [1.000000

In [129]:
X_predict["Loss Chance"] = predictions[:,0]*100
X_predict["Win Chance"] = predictions[:,1]*100


In [130]:
X_predict

distance  track  age  odds  pp_start  j_starts  j_first  j_second  \
0        900      0    7   6.0         7        28        3         1   
1        650      1    3   5.0         1        63        9         6   
2        550      1    4  10.0         2        63        9         6   
3        500      0    6  30.0        10         2        0         0   
4        550      1    3  12.0         3        12        1         1   
5        500      0    4   3.5         5        19        1         4   
6        500      1    2  20.0         7         5        0         1   
7        550      1    2   4.0         4        42       10         3   
8        900      0    4   6.0         1        42       10         3   
9        500      0    4   2.5         6        42       10         3   
10       500      1    2  20.0         5        42       10         3   
11       550      1    5  10.0         4         0        0         0   
12       500      1    2  10.0         3        40        4         4   
13       500      0    3   8.0         4        40        4         4   
14       650      1    3   5.0         7        40        4         4   
15       550      1    4   2.0         5        40        4         4   
16       550      1    2   2.5         2        31        2         5   
17       500      0    3  20.0         7        31        2         5   
18       500      0    3  12.0         1        52        8         3   
19       650      1    3   8.0         2        52        8         3   
20       500      1    2   3.5         9        52        8         3   
21       550      1    4   6.0         7        37        6         4   
22       500      1    2   2.5         8        37        6         4   
23       550      1    2  20.0         7        37        6         4   
24       500      0    3  12.0         3         0        0         0   
25       500      1    2   5.0         1        40        2         7   
26       500      1    2  10.0         4        35        7         7   
27       550      1    2  12.0         6        35        7         7   
28       650      1    4  12.0         4        35        7         7   
29       500      0    5  12.0         9        10        2         1   
30       550      1    2   3.5         1        10        2         1   
31       900      0    5   5.0         8        32        0         4   
32       650      1    3   6.0         6        51        4         7   
33       900      0    6   6.0         6        51        4         7   
34       900      0    6  15.0         4        20        3         1   
35       550      1    3   3.0         6        39        2         7   
36       550      1    2   2.0         5        39        2         7   
37       500      1    2   5.0         2        40        4         3   
38       650      1    3   2.0         3        40        4         3   
39       900      0    5   6.0         3        40        4         3   
40       900      0    6   3.5         5        59        7         8   
41       550      1    2   8.0         3        59        7         8   
42       500      1    2   4.5         6        59        7         8   
43       550      1    4   2.5         1        59        7         8   
44       650      1    3   2.5         5        59        7         8   
45       500      0    4   4.0         8        59        7         8   
46       900      0    6   3.0         2        35        4         3   
47       500      0    4   4.5         2        35        4         3   

    j_third  j_total_win_amt      ...       j_top_3_perc  t_starts  t_first  \
0         1            66200      ...               0.18         5        2   
1         5           314435      ...               0.32        12        2   
2         5           314435      ...               0.32         4        0   
3         0              690      ...               0.00         1        0   
4         2            25830   